# Generated by Django 3.2 on 2024-02-29 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authtoken',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='updateemailtoken',
            old_name='user',
            new_name='profile',
        ),
    ]
